# Linear Algebra, The Essentials!

In this workbook we will introduce just enough of the basics of linear 
algebra. This is because Vector-Symbolic Architectures (VSAs) are really just fancy first-year linear algebra and matrix manipulation. 


Aside from the primer here, we recommend checking out:

> [1] T. A. Garrity, All the mathematics you missed: but need to know for 
> graduate school. Cambridge, UK ; New York, NY: Cambridge University Press, 
> 2002.

> [2] C. C. Aggarwal, Linear Algebra and Optimization for Machine Learning: 
> A Textbook. Springer International Publishing, 2020.


## What is Linear Algebra?

*Linear algebra* is a generalization of the the simple operations over 
matrices and vectors that you may have learned about in your mathematics courses.

The three fundamental objects that are used in the study of vector-symbolic
architectures are the following:

1. *Scalars*, which are the regular numbers you know and love: e.g., $1$, 
$2$, $3$, and so on. These have the standard operations that you know and love
too: we can add them like $1 + 2$, multiply them by $3(4)$, and so on, and so
forth. In order to keep it clear when we're talking about scalars, the 
standard convention is to talk about scalars using Greek letters,
$\alpha, \beta, \gamma, \dots, \omega$.

2. *Vectors* can be thought of as *lists* of *scalars*. Each individual
element of a vector is known as an *element*, *component*, or *coordinate*. We
denote vectors by lower case Latin letters, and write them 
putting square brackets around the a comma-separated list
of the elements:
$$
v = [1, 2, 3, 4, 5].
$$
We say that a vector with $n$ elements inside is $n$*-dimensional*. So, the
above vector $[1,2,3,4,5]$ is a $5$-dimensional vector. In order to talk
about elements inside of the vector, we need to use an *index*. 
So $v_1 = 1$, $v_2 = 2$, etc.

3. *Matrices* are vectors which have other vectors are their entries. Matrices
are denoted with upper-case letters $A, B, \dots, Z$. For a matrix $A$ with
$n$-rows and $d$-columns, we say that $A$ is an $n \times d$-dimensional
matrix, or just an $n \times d$ matrix for short. To write out a matrix,
we extend the previous vector notation to include both rows and columns:
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}.
$$
To talk about elements inside of the matrix, we need to know both the row
and the column of the item. So, we need two numbers. For the $3 \times 3$
matrix $A$ above, the item at the $(1, 1)$ index, or $A_{11} = 1$, $A_{12} = 2$,
$A_{13}=3$. The fist index denotes *which row to look at*, and the second 
index picks out *which column to look at*.

Scalars, vectors, and matrices can be talked about in Python using
the standard library implementation of `list`, but this is very slow. So, smarter
minds than both you and I have come together and made something called a 
*library*, which is a collection of function, class, and variable definitions
for us to use. The main linear algebra library used in scientific contexts
is known as [numpy](https://numpy.org). `numpy` has powered many scientific
achievements: for example, it is a library used by scientists
[who produced the first picture of the event horizon of a black hole](https://numpy.org/case-studies/blackhole-image/).

The typical way of interacting with `numpy` is to begin with the following
incantation:

In [13]:
import numpy as np

This allows us to reference `numpy` functions and methods by the shorter name,
`np`. Secondly, in order to see how vectors look, we will be using a very
popular graphing library: `matplotlib`. It similarly involves an incantation,
but this is a bit more complex:

In [14]:
# import the library and alias it
import matplotlib.pyplot as plt
# special python "magic" command
# this puts `plt.show()` at the end of every frame
%matplotlib inline 

We can initialize vectors in several ways: the simplest is to just provide a list:

In [15]:
np.array([1, 2, 3])     # initialize a vector from a list

array([1, 2, 3])

In [16]:
np.zeros(3)             # initialize an empty vector

array([0., 0., 0.])

In [17]:
np.ones(3)              # initialize a vector of ones

array([1., 1., 1.])

Matrices, we have to specify the dimensionality:

In [18]:
np.array(
    [[1,2,3],
     [4,5,6],
     [7, 8, 9]]
)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

We are also able to create vectors of random elements as well. To do this,
we use the `numpy.random.uniform` function.

In [31]:
np.random.uniform(size=(3, 10))

array([[0.68241471, 0.73596606, 0.19176839, 0.93733974, 0.10246939,
        0.2462846 , 0.01834118, 0.15028463, 0.66504443, 0.36327406],
       [0.80612254, 0.25802244, 0.92828889, 0.94222988, 0.50352095,
        0.97501468, 0.44155854, 0.33163473, 0.11029503, 0.27802545],
       [0.95126912, 0.29606477, 0.85703117, 0.40981307, 0.0982014 ,
        0.56351136, 0.04158052, 0.02254761, 0.35040696, 0.60679058]])

The dimensionality of a `np.array` can be gotten by calling the function `.shape`:

In [32]:
np.ones((1, 10)).shape

(1, 10)

### Exercises

1. Initialize a $10 \times 10$ matrix of zeros.
2. Initialize a $100$-dimensional vector of ones.
3. Create a $27 \times 5$-dimensional vector with random elements.

## Operations on vectors

What can we do with vectors? The first, simplest operations are *element-wise
addition* and *element-wise multiplication* (also known as the [*Hadamard product*](https://en.wikipedia.org/wiki/Jacques_Hadamard)).
For two vectors $x$ and $y$ of the same dimension $n$ the element-wise sum 
is:
$$
x + y = [x_1 + y_1, x_2 + y_2, \dots, x_n + y_n].
$$

To do this in `python`, it's surpisingly very simple:

In [21]:
x = np.ones(3)      # [1, 1, 1]
y = np.ones(3)      # [1, 1, 1]

# you just do the same as with scalars:
x + y               # should be: [2, 2, 2]

array([2., 2., 2.])

The next basic operation over vectors is similar: element-wise multiplication.
Like element-wise addition, it is equally simple:

For two $n$-dimensional vectors $x$ and $y$, the element-wise product is:
$$
x \odot y = [x_1 * y_1, x_2 * y_2, \dots, x_n * y_n].
$$

In [22]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x * y               # should be [4, 10, 18]

array([ 4, 10, 18])

Note that both of these operations require that the two vectors are $n$-dimensional,
otherwise we get an error:

In [23]:
x = np.ones(2)
y = np.ones(3)

x + y

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

The next basic vector operation that are used in the study of cognition
with vector-symbolic architectures is the *dot product*. You might be familiar
with the dot product previous math courses, as it has a familiar form: for 
two $n$-dimensional vectors $x$ and $y$, the dot product is:
$$
x \cdot y = \sum_{i=1}^n x_i y_i.
$$
As an example, consider the vectors $x = [1, 2, 3]$ and $y = [4, 5, 6]$. The dot
product, is:
$$
\begin{align*}
x \cdot y &= \sum^3_{i=1} x_i y_i \\
&= 1 (4) + 2 (5) + 3 (6) \\
&= 4 + 10 + 18 \\
&= 14 + 18 \\
&= 32.
\end{align*}
$$
Note first that the dot product of two vectors doesn't make another vector like
our other operations. Rather, it takes two $n$-dimensional vectors and
turns it into a number.

What does this number mean? If we think about the simple case of $2$-dimensional
vectors $x = [1, 2]$ and $y = [3, 4]$, then the dot product between vectors
is just the sum of the products $x$-coordinates and the $y$-coordinates. Where
do we see this? Recall, the distance of a point given it's coordinates
from the original can be calculated via the Pythagorean theorem as:
$$
d = \sqrt{x_1^2 + x_2^2}.
$$
We denote this as the *magnitude* of the vector $x$, $\|x\|$. And the inner
term there, if we square it and get rid of the root, gives us $x_1^2 + x_2^2$,
which is just the dot product of $x$ with itself: $x \cdot x$. 

Then what is $x \cdot y$? We define $x \cdot y$ as product of the magnitudes
of $x$ and $y$ with the cosine of the angle $\theta$ between $x$ and $y$:
$$
x \cdot y = \sum_i x + y = \| x \| \| y \| \cos (\theta).
$$

This definition leads us to the final important function between vectors:
*cosine similarity*. This is the measure of the angle between the two 
vectors, with $1$ for the two vectors being *colinear* (on the same line), and 
$0$ for being orthogonal (they form a right angle). 

We can derive this measure thus:
$$
\begin{align*}
x \cdot y &= \| x \| \|y \| \cos (\theta) \\
\frac{x \cdot y}{\|x \| \|y \|} &= \cos (\theta).
\end{align*}
$$
We can define this operation as:
$$
\text{cosine\_similarity}(x, y) := \frac{x \cdot y}{\| x \| \| y\|}.
$$

Only two of these elementary operations are implemented in `numpy`; implementing
cosine similarity will be left as an exercise for the reader.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# the dot product is a method
x.dot(y)

32

In [ ]:
# a more complex way of getting the same result that we will learn about
# later on is the following:
x @ y.T
# these are some special operations, but just note that you can do it this way

32

### Exercises

1. Implement element-wise addition as a function.
2. Implement element-wise multiplication as a function.
3. Implement the dot product for vectors.

## Operations on matrices

Next we will begin with operations on matrices, which are remarkably similar
to the vector in the beginning. The element-wise sum for $n \times d$ matrices
$A$ and $B$ is just the element-wise multiplication of the rows of $A$ with
the rows of $B$ (or, equivalently, the columns of $A$ with the columns of $B$):
$$
\begin{align*}
A + B &= \begin{bmatrix} 
a_{11} & a_{12} & \dots & a_{1d} \\
a_{21} & a_{22} & \dots & a_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \dots & a_{nd}
\end{bmatrix}
+ \begin{bmatrix} 
b_{11} & b_{12} & \dots & b_{1d} \\
b_{21} & b_{22} & \dots & b_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \dots & b_{nd}
\end{bmatrix} \\
&= 
\begin{bmatrix} 
a_{11} + b_{11} & a_{12} + b_{12} & \dots & a_{1d} + b_{1d} \\
a_{21} + b_{21} & a_{22} + b_{22} & \dots & a_{2d} + b_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} + b_{n1} & a_{n2} + b_{n2} & \dots & a_{nd} + b_{nd}
\end{bmatrix}
\end{align*}
$$

This is the same for element-wise multiplication between two matrices:
$$
\begin{align*}
A \odot B &= \begin{bmatrix} 
a_{11} & a_{12} & \dots & a_{1d} \\
a_{21} & a_{22} & \dots & a_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \dots & a_{nd}
\end{bmatrix}
* \begin{bmatrix} 
b_{11} & b_{12} & \dots & b_{1d} \\
b_{21} & b_{22} & \dots & b_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \dots & b_{nd}
\end{bmatrix} \\
&= 
\begin{bmatrix} 
a_{11} * b_{11} & a_{12} * b_{12} & \dots & a_{1d} * b_{1d} \\
a_{21} * b_{21} & a_{22} * b_{22} & \dots & a_{2d} * b_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} * b_{n1} & a_{n2} * b_{n2} & \dots & a_{nd} * b_{nd}
\end{bmatrix}
\end{align*}
$$

In [ ]:
# Element-wise addition of matrices
a = np.ones((3, 3))
b = np.ones((3, 3))
a + b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
# Element-wise multiplication
a = np.array([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

a * b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

But these aren't the only operations that are available for matrices. Recall,
we had an alternative form of the dot product for two $d$-dimensional vectors
$x$ and $y$,
$$
x y^T
$$
(where in the code we used a funny symbol `@` to denote this special kind
of product). This is *matrix multiplication*. For an $n \times d$ matrix $A$
and a $d \times k$ matrix $B$, the matrix product of $A$ and $B$ is an 
$n \times k$ matrix $AB$:
$$
\begin{align*}
A B &= \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1d} \\
a_{21} & a_{22} & \dots & a_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \dots & a_{nd}
\end{bmatrix}
\begin{bmatrix}
b_{11} & b_{12} & \dots & b_{1d} \\
b_{21} & b_{22} & \dots & b_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \dots & b_{nd}
\end{bmatrix}\\
&= \begin{bmatrix}
a_{11} b_{11} + a_{12} b_{21} + \dots + a_{1d} b_{n1} & a_{11} b_{12}+ a_{12} b_{22} + \dots + a_{1d} b_{n2} & \dots & a_{11}  b_{1d} + a_{12} b_{2d} + \dots + a_{1d} b_{nd} \\
a_{21} b_{11} + a_{22} b_{21} + \dots + a_{2d} b_{n1} & a_{21} b_{12}+ a_{22} b_{22} + \dots + a_{2d} b_{n2} & \dots & a_{21}  b_{1d} + a_{22} b_{2d} + \dots + a_{2d} b_{nd} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} b_{11} + a_{n2} b_{21} + \dots + a_{nd} b_{n1} & a_{n1} b_{12}+ a_{n2} b_{22} + \dots + a_{nd} b_{n2} & \dots & a_{n1}  b_{1d} + a_{n2} b_{2d} + \dots + a_{nd} b_{nd} \\
\end{bmatrix}.
\end{align*}
$$
This is a bit unwieldy, but the astute reader will notice a specific pattern:
we iterate over each *row* in $A$ and take the dot product with every *column*
in $B$. Graphically, the procedure works like below:

![alt text](../../../Matrix_multiplication_diagram_2.png "Matrix multiplication, from Wikipedia")

Matrix multiplication with `numpy` is very easy, as we have seen above.

In [28]:
A = np.random.uniform(size=(4, 5)) # initialize a random vector
B = np.random.uniform(size=(5, 4)) # another random vector
print(f"{A = }")
print(f"{B = }")
print(f"{A @ B = }")
print(f"{(A@B).shape = }")

A = array([[0.24722361, 0.77351516, 0.16902154, 0.6322197 , 0.52380344],
       [0.0241637 , 0.5063746 , 0.35809555, 0.67655046, 0.97630666],
       [0.73301193, 0.87380516, 0.90333692, 0.34339587, 0.51295059],
       [0.08876799, 0.4058305 , 0.77923558, 0.20867205, 0.01856795]])
B = array([[0.71144555, 0.07533576, 0.18180619, 0.21073147],
       [0.46430317, 0.85345778, 0.93046243, 0.95825236],
       [0.77547804, 0.81300566, 0.93542743, 0.23740964],
       [0.41320611, 0.4070461 , 0.20259505, 0.7189205 ],
       [0.43468337, 0.35785536, 0.76688268, 0.01181729]])
A @ B = array([[1.15502987, 1.26099121, 1.45256134, 1.2941535 ],
       [1.23393678, 1.34988724, 1.6963065 , 1.07326533],
       [1.99259089, 1.85873592, 2.25425834, 1.45919144],
       [0.95015781, 1.07815332, 1.17918231, 0.74283031]])
(A@B).shape = (4, 4)


Another operation that will be useful for manipulating matrix is the 
*transpose* operation. For an $n \times d$ matrix $A$, the transpose of $A$,
denoted by $A^T$, is a $d \times n$ matrix. I'll write out what it looks like,
but an intuition here is that we flip the matrix down and the over.
$$
\begin{align*}
A^T &= \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1d} \\
a_{21} & a_{22} & \dots & a_{2d} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \dots & a_{nd}
\end{bmatrix}^T \\
&= \begin{bmatrix}
a_{11} & a_{21} & \dots & a_{n1} \\
a_{12} & a_{22} & \dots & a_{n2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1d} & a_{2d} & \dots & a_{nd}
\end{bmatrix}
\end{align*}
$$
Doing this in `numpy` is also very easy:

In [30]:
A = np.random.uniform(size=(3, 2)) # random matrix
print(f"{A = }")
print(f"{A.T = }")

A = array([[0.35334897, 0.31752937],
       [0.1737748 , 0.55470293],
       [0.97313347, 0.04868536]])
A.T = array([[0.35334897, 0.1737748 , 0.97313347],
       [0.31752937, 0.55470293, 0.04868536]])


### Exercises

1. Initialize a $2 \times 5$ matrix with random elements.
2. Implement element-wise addition for matrices.
3. Implement element-wise multiplication for matrices.
4. Implement matrix multiplication.

## Everything is a matrix

Now that we have an understanding of the basic operations of linear algebra, 
an important point about the theory of linear algebra is that all of the objects
discussed are different subtypes of the same overarching thing: matrices,
vectors, and scalars are all *matrices*. 

A $d$-dimensional vector $v$ can be thought of as a $d \times 1$ dimensional 
matrix. Vectors so formed are called *column matrices*. $1 \times d$ vectors are
called *row vectors*. In linear algebra we assume all vectors are column
vectors by default unless otherwise specified.

> [Problem] For two $d$-dimensional column vectors $x$ and $y$,
> show that $x y^T$ is equivalent to $x \cdot y$.